/**
 * @file components/DietPlanDisplay.jsx
 * @description Renders a full 7-day AI-generated diet plan as a responsive
 *              CSS Grid calendar layout.
 *
 * Props:
 *   weekSchedule {object} — The weekSchedule JSON from the DietPlan document.
 *                           Expected shape:
 *                           {
 *                             monday:    { breakfast, lunch, dinner },
 *                             tuesday:   { ... },
 *                             ...
 *                             sunday:    { ... }
 *                           }
 *   generatedAt  {string} — ISO date string for the plan creation timestamp.
 */

import "./DietPlanDisplay.css";

// ─── Constants ────────────────────────────────────────────────────────────────

const DAYS_ORDER = [
  "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday",
];

const DAY_LABELS = {
  monday:    "Monday",
  tuesday:   "Tuesday",
  wednesday: "Wednesday",
  thursday:  "Thursday",
  friday:    "Friday",
  saturday:  "Saturday",
  sunday:    "Sunday",
};

const MEAL_META = {
  breakfast: { icon: "🌅", label: "Breakfast" },
  lunch:     { icon: "☀️",  label: "Lunch"     },
  dinner:    { icon: "🌙", label: "Dinner"    },
};

// ─── Sub-Components ───────────────────────────────────────────────────────────

/**
 * MealSlot — A single meal card inside a day column.
 */
const MealSlot = ({ type, text }) => {
  const meta = MEAL_META[type] || { icon: "🍽", label: type };
  return (
    <div className={`dpd-meal dpd-meal--${type}`}>
      <div className="dpd-meal__header">
        <span className="dpd-meal__icon" aria-hidden="true">{meta.icon}</span>
        <span className="dpd-meal__label">{meta.label}</span>
      </div>
      <p className="dpd-meal__text">{text || "—"}</p>
    </div>
  );
};

/**
 * DayColumn — One day's column in the calendar grid.
 */
const DayColumn = ({ day, dayData, isToday }) => {
  const meals = dayData || {};
  return (
    <div className={`dpd-day ${isToday ? "dpd-day--today" : ""}`}>
      <div className="dpd-day__header">
        <span className="dpd-day__name">{DAY_LABELS[day]}</span>
        {isToday && <span className="dpd-day__today-badge">Today</span>}
      </div>
      <div className="dpd-day__meals">
        <MealSlot type="breakfast" text={meals.breakfast} />
        <MealSlot type="lunch"     text={meals.lunch}     />
        <MealSlot type="dinner"    text={meals.dinner}    />
      </div>
    </div>
  );
};

// ─── Main Component ───────────────────────────────────────────────────────────

const DietPlanDisplay = ({ weekSchedule, generatedAt }) => {
  if (!weekSchedule || Object.keys(weekSchedule).length === 0) {
    return (
      <div className="dpd-empty">
        <div className="dpd-empty__icon">🥗</div>
        <p className="dpd-empty__text">No AI diet plan generated yet.</p>
        <p className="dpd-empty__sub">
          Use the "Generate AI Plan" button to create your personalised 7-day schedule.
        </p>
      </div>
    );
  }

  // Determine today's day name (lowercase) so we can highlight it
  const todayKey = new Date()
    .toLocaleDateString("en-US", { weekday: "long" })
    .toLowerCase();

  return (
    <div className="dpd-container">
      {/* ── Header ── */}
      <div className="dpd-header">
        <div className="dpd-header__left">
          <span className="dpd-header__icon" aria-hidden="true">🤖</span>
          <div>
            <h2 className="dpd-header__title">Your AI-Generated Diet Plan</h2>
            {generatedAt && (
              <p className="dpd-header__sub">
                Generated on{" "}
                {new Date(generatedAt).toLocaleDateString("en-US", {
                  weekday: "long",
                  year:    "numeric",
                  month:   "long",
                  day:     "numeric",
                })}
              </p>
            )}
          </div>
        </div>
        <span className="dpd-header__badge">✦ Powered by Gemini AI</span>
      </div>

      {/* ── Legend ── */}
      <div className="dpd-legend">
        {Object.entries(MEAL_META).map(([type, meta]) => (
          <span key={type} className={`dpd-legend__item dpd-legend__item--${type}`}>
            {meta.icon} {meta.label}
          </span>
        ))}
      </div>

      {/* ── 7-Day Grid ── */}
      <div className="dpd-grid" role="grid" aria-label="7-day meal plan">
        {DAYS_ORDER.map((day) => (
          <DayColumn
            key={day}
            day={day}
            dayData={weekSchedule[day]}
            isToday={day === todayKey}
          />
        ))}
      </div>

      {/* ── Disclaimer ── */}
      <p className="dpd-disclaimer">
        ⚕ This plan is generated by AI and tailored to your health profile. Always consult a
        licensed dietician before making significant dietary changes.
      </p>
    </div>
  );
};

export default DietPlanDisplay;
